### ISSUE TITLE
Upgrade node

### ISSUE THREAD

**Issue by arosequist** [supplypike/docker-node-service#2]
The latest version of node is 9.3.0 (8.9.3 LTS). What would we need to do to upgrade this image from version 6 to a more recent one? They've added some nice new features (and I assume performance improvements and bugfixes) and we're starting to run into libraries that no longer support v6.

**Comment by Bekt** [comment]
The goal of this shared image was to 1) provide a node image with pre-agreed standards 2) inject some node configs/modules (performance, security, monitoring, etc) so that each service owner doesn't have to worry about with up keeping.

We never did #2 so at this point this image isn't doing much. If we still want to keep this shared image (I vote we should), we need to agree on how to version/tag this. Some options:

  1. Our own versioning: node-service:1, node-service:2, node-service:3, etc
  2. Mirror major node versions: node-service:v6, node-service:v8, node-service:v8-slim, etc.

I kind of lean towards #2, what do y'all think? We can support multiple versions with separate Dockerfiles (see PR #1)

**Comment by Bekt** [comment]
Also this repo should probably be private at some point, I don't really want to support other orgs. (I doubt anybody uses it 😆)

**Comment by chris72205** [comment]
I like option 2 as well.  Is there an advantage to multiple Dockerfiles as opposed to using different branches for each version we want (and letting Docker hub build/tag them accordingly)?

**Comment by Bekt** [comment]
The end result would be the same -- DockerHub can (auto) build different tags from different Dockerfiles as well. I'm not a fan of branch per version as branches can easily get stale and can be harder to maintain when it's time for cherry-picking or new features.

**Comment by chris72205** [comment]
Ah nice, I didn't know it could do that.

**Comment by arosequist** [comment]
Approach #2 (with separate Dockerfiles) sounds good to me, too.

**Comment by Bekt** [comment]
Does anybody wanna give it a try? The official [docker-node](https://github.com/nodejs/docker-node/tree/master) uses templates to generate the Dockerfiles.

I think we can get away with a single template, something like:

Dockerfile.template
```
FROM {{ base }}
ENV NPM_CONFIG_LOGLEVEL warn

WORKDIR /opt/cs-service/

EXPOSE 40404

CMD ["npm", "start"]
```

And from this generate out/Dockerfile.v6, out/Dockerfile.v8, etc. Maybe use something more friendlier than sed (docker-node uses it). I can help whoever wants to take a stab.

**Comment by Bekt** [comment]
fyi @evanrblack is working on this.

**Comment by Bekt** [comment]
https://github.com/casestack/docker-node-service/pull/3

**Comment by Bekt** [comment]
These tags will now point to the latest parent node version.

```
$ docker run -it casestack/node-service:6 node --version
v6.12.3

$ docker run -it casestack/node-service:8 node --version
v8.9.4
```
